#!/bin/bash

#
#  Bash Script to Manage /etc/docker/daemon.json file
#

mkdir -p /etc/docker && tee /etc/docker/daemon.json > /dev/null <<EOF

{
  "debug": false,
  "dns": ["180.76.76.76", "1.2.4.8", "119.29.29.29", "223.5.5.5"],
  "max-concurrent-downloads": 10,
  "max-concurrent-uploads": 10,
  "oom-score-adjust": -1000,
  "registry-mirrors": [
    "https://mirror.baidubce.com",
    "https://hub-mirror.c.163.com",
    "https://docker.mirrors.ustc.edu.cn"
  ]
}

EOF
